# Turn on validation, so we can use import:
version: ~> 1.0

jdk:
- openjdk8
import: land-of-apps/land-of-apps:travis/java-imports.yml

script:
- mvn test -Plight-test -Dmaven.test.failure.ignore=true
